Sync with 2018.10.08-1
 * allow docker if user in 'docker run' same as user in image metadata
 * yaml: Use "Safe" versions of Loader/Dumper
 * remove kafka
 * watchdogd: Use intrinsic reboot support
 * Remove import from aliases
 * Lazily create zkclient in presence service so that it does not try to
   blackout a node during zk disconnection.
 * Added implementation of group based authorizer.
 * Added config cell option to specify zk auth scheme.
 * Make fs.write_safe exception safe.
 * Set connect timeout on gssapiprotocol.

diff --git a/lib/python/treadmill/templates/kernel-watchdog-test b/lib/python/treadmill/templates/kernel-watchdog-test
--- a/lib/python/treadmill/templates/kernel-watchdog-test
+++ b/lib/python/treadmill/templates/kernel-watchdog-test
@@ -1,11 +1,11 @@
-#!/bin/sh
+#!/bin/ksh
 
 TYPE=$1
 TEST_RET_CODE=$2
 
-# watchdog reserves return value -10 ~ -1, ref https://linux.die.net/man/8/watchdog
-WATCHDOG_RESERVED=(246 247 248 249 250 251 252 253 254 255)
-REPLACEMENT=245
+# watchdog reserves return value -9 ~ -1, ref https://linux.die.net/man/8/watchdog
+WATCHDOG_RESERVED=(247 248 249 250 251 252 253 254 255)
+REPLACEMENT=246
 
 if [ "$TYPE" == "test" ]; then
     echo "Trigger test {{ name }}"
@@ -13,14 +13,13 @@ if [ "$TYPE" == "test" ]; then
     ret=$?
     for reserved in "${WATCHDOG_RESERVED[@]}"; do
         if [ "$ret" -eq "$reserved" ]; then
-            exit $REPLACEMENT
+            exit ${REPLACEMENT}
         fi
     done
-    exit $ret
+    exit ${ret}
 fi
 
-if [ "$TYPE" == "repair" ]; then
-    echo "Test {{ name }} failed with $TEST_RET_CODE"
-    {{ reboot }}
-    exit -2
+if [ "${TYPE}" == "repair" ]; then
+    echo "Test {{ name }} failed with ${TEST_RET_CODE}"
+    exit ${TEST_RET_CODE}
 fi
